### ISSUE TITLE
Github replaces a colon with a dot

### ISSUE THREAD

**Issue by ericwoud** [7Ji/archrepo#2]
Hi,

I've done something similar, but github mangles the filename. It replaces a colon with a dot.

So you cannot:

```
sudo rm /var/cache/pacman/pkg/ffmpeg-mpp*

sudo pacman -Syu ffmpeg-mpp
```
It cannot find the file, the filename changed.

**Comment by 7Ji** [comment]
Yes, indeed, thanks for reminding, I just found that. I don't use the repo myself, as I have a server in LAN and they serve the same pacakges so I didn't notice this.

That could be fixed by either modifying the PKGBUILD to remove epoch, or renaming the packages before adding them to DB. Speaking of which why did `ffmpeg-mpp` even need an epoch in the first place? Epoch is only ever needed for a few scenarios like when version numbering           scheme of a package changes? @hbiyik

**Comment by 7Ji** [comment]
OK so that epoch was carried all the way from Arch... I kinda wonder why would Github do that though... Using colon in URL doesn't seem to break anything as that was how Arch/ALARM official repos work

**Comment by ericwoud** [comment]
I ended up in editing the source of `repo-add` and save a different version of it to use to create the db for github.

**Comment by hbiyik** [comment]
ugh, this is ugly, i think removing the epoch will cause the packages not to be updated if someone has an older version with epoch=2, in my packages only ffmpeg-mpp has it and itherits this from ffmpeg, currently not needed at all.

**Comment by hbiyik** [comment]
may be i should just remove epoch, people can force reinstall anyways... i am not sure.

**Comment by 7Ji** [comment]
> I ended up in editing the source of `repo-add` and save a different version of it to use to create the db for github.

I don't think that's needed, you only need to `repo-add` pkgs' with their name already replaced, like:
https://github.com/7Ji/archrepo/blob/629213184f835d6098f05eb5e0b0d7cde98d5d7f/scripts/compress_and_sign.fish#L8
